name: Release package

on:
  push:
    branches: [ master ]

jobs:
  release-package:
    runs-on: ubuntu-latest
    env:
      # NPM_CONFIG_TOKEN: ${{secrets.NPM_CONFIG_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_CONFIG_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish --access=public
